spring.application.name=Weather-App-bySpark
weather.api.key=c632b27ea18048d0bc0112921260110
weather.api.url=http://api.weatherapi.com/v1/current.json
forecast.api.url=http://api.weatherapi.com/v1/forecast.json